=== weimingtom/galaxy_fork/galaxywpf/script/scene-def.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--
	<xs:simpleType id="imgType" name="imgType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bust" />
			<xs:enumeration value="fullscreen" />
			<xs:enumeration value="middle" />
		</xs:restriction>
	</xs:simpleType>
	-->
	<xs:simpleType id="varOper" name="varOper">
		<xs:restriction base="xs:string">
			<xs:enumeration value="add" />
			<xs:enumeration value="dec" />
			<xs:enumeration value="set" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType id="compType" name="varType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string" />
			<xs:enumeration value="int" />
			<xs:enumeration value="float" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType id="varType" name="compType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gt" />
			<xs:enumeration value="lt" />
			<xs:enumeration value="equal" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="scene">
		<xs:complexType>
			<xs:sequence>
				<!--场景私有变量-->
				<xs:element minOccurs="0" maxOccurs="unbounded" name="var-def">
					<xs:complexType>
						<xs:attribute name="name" use="required"/>
						<xs:attribute name="type" type="varType" default="int" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="section">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="1" name="gotoscene" type="xs:string" />
							<xs:element minOccurs="0" maxOccurs="1" name="img">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="1" name="effect" type="xs:string" />
										<xs:element minOccurs="0" maxOccurs="1" name="width" type="xs:unsignedByte" />
										<xs:element minOccurs="0" maxOccurs="1" name="height" type="xs:unsignedByte" />
										
										<xs:element minOccurs="0" maxOccurs="1" name="x" type="xs:int" />
										<xs:element minOccurs="0" maxOccurs="1" name="y" type="xs:int" />
										<!--<xs:element minOccurs="0" maxOccurs="1" name="type" type="imgType" />-->
									</xs:sequence>
									<xs:attribute name="width" type="xs:int" use="optional" />
									<xs:attribute name="height" type="xs:int" use="optional" />
									<xs:attribute name="x" type="xs:int" use="optional" />
									<xs:attribute name="y" type="xs:int" use="optional" />
									<!--><xs:attribute name="type" type="imgType" /> -->
									<xs:attribute name="effect" type="xs:unsignedByte" use="optional" />
									<xs:attribute name="source" type="xs:unsignedByte" use="optional" />
									<xs:attribute name="visiable" type="xs:boolean" use="optional" />
									<xs:attribute name="bust" type="xs:boolean" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" name="say">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="1" name="speaker" type="xs:string" />
										<xs:element minOccurs="0" maxOccurs="1" name="select-title" type="xs:string" />
										<xs:element minOccurs="0" maxOccurs="1" name="select">
											<xs:complexType>
												<xs:sequence>
													<xs:element minOccurs="1" maxOccurs="unbounded" name="item">
														<xs:complexType mixed="true">
															<xs:sequence>
																<xs:element minOccurs="0" maxOccurs="1" name="gotosection" type="xs:string" />
															</xs:sequence>
															<xs:attribute name="next-section" type="xs:string" use="required" />
															<xs:attribute name="id" type="xs:string" use="required" />
														</xs:complexType>	
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="speaker" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" name="sound" type="xs:string" />
							<xs:element maxOccurs="1" minOccurs="0" name="var-oper">
								<xs:complexType>
									<xs:attribute name="oper" type="varOper" default="set" />
									<xs:attribute name="target" type="xs:string" use="required" />
									<xs:attribute name="value" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="if">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="tosection" type="xs:string" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="left" type="xs:string" use="required" />
									<xs:attribute name="comp" type="compType" default="equal" />
									<xs:attribute name="right" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedByte" use="required" />
						<xs:attribute name="next-section" type="xs:string" use="required"/>
						<!--<xs:attribute name="visiable" type="xs:boolean" use="optional" />-->
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:unsignedByte" use="required" />
			<xs:attribute name="bgimg" type="xs:string" use="required" />
			<xs:attribute name="bgm" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== weimingtom/galaxy_fork/galaxy/script/scene0.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="scene-def.xsd"  
	id="0" bgimg="girls.jpg" bgm="03.wma">
   <!-- 贴张图 -->
   <section id="0">
       <img x="0" y="0" width="640" height="480">loli1.jpg</img>
       <say speaker="某萝莉">
	   你拍一，我拍一，春哥爷们打飞机
	   </say>
       <sound>sakura.mp3</sound>
   </section>
	<section id="1">
		<img x="0" y="0" width="640" height="480">loli1.jpg</img>
		<say speaker="某萝莉">
			你拍二，我拍二，春哥有个长老二
		</say>
		<sound>sakura.mp3</sound>
	</section>
	<section id="2">
		<img x="0" y="0" width="640" height="480">loli2.jpg</img>
		<say speaker="某萝莉">
			你拍三，我拍三，春哥JB能穿山
		</say>
		<sound>sakura.mp3</sound>
	</section>
	<section id="3">
		<img x="0" y="0" width="640" height="480">loli2.jpg</img>
		<say speaker="某萝莉">
			你拍四，我拍四，春哥连牛都能日
		</say>
		<sound>sakura.mp3</sound>
	</section>
	<section id="4">
		<img x="0" y="0" width="640" height="480">loli6.jpg</img>
		<say speaker="某萝莉">
			你拍五，我拍五，春哥一干到中午
		</say>
		<sound>sakura.mp3</sound>
	</section>
	<section id="5">
		<img x="0" y="0" width="640" height="480">loli6.jpg</img>
		<say speaker="某萝莉">
			你拍六，我拍六，春哥日死老黄牛
		</say>
		<sound>sakura.mp3</sound>
	</section>
	<section id="6">
       <gotoscene>scene0</gotoscene>
   </section>
</scene>

=== weimingtom/galaxy_fork/galaxywpf/script/scene4.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="scene-def.xsd"
	id="0" bgimg="1.JPG" bgm="03.wma">
	<!-- 贴张图 -->
	<var-def name="life" type="int"/>
	<section id="0" next-section="null">
		
		<say speaker="翠翠">
			<select-title>
				你对翠野鼠怎么看？
			</select-title>
			<select>
				<item next-section="2" id="2">
					好人
				</item>
				<item next-section="2" id="2">
					坏人
				</item>
				<item next-section="3" id="3">
					翠野鼠是什么东西？可以吃吗？
				</item>
			</select>
		</say>
		<var-oper target="life" oper="set" value="0" />
	</section>
	<section id="2" next-section="0">
		<say speaker="翠翠">翠野鼠给你机会重新答一次</say>
		<var-oper target="life" oper="dec" value="1"/>
		<if left="life" comp="lt" right="0">
			<tosection>4</tosection>
		</if>
	</section>
	<section id="3" next-section="0">
		<say speaker="翠翠">恭喜答对，得到翠野鼠嘴一个</say>
		<var-oper target="life" oper="add" value="10"/>
	</section>
	<section id="4" next-section="0">
		<say speaker="翠翠">变量值小于零</say>
	</section>
</scene>

=== weimingtom/galaxy_fork/galaxy/script/scene3.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="scene-def.xsd"
	id="0" bgimg="ai.JPG" bgm="03.wma">
	<!-- 贴张图 -->
	<section id="0" next-section="1">
		<say speaker="爱">
			君好像很忙呢，要不要犒劳一下？
		</say>
	</section>
	<section id="1" next-section="null">
		<say speaker="爱">
			<select-title>
				你喜欢我吗？
			</select-title>
			<select>
				<item next-section="3" id="1">
					是
				</item>
				<item next-section="2" id="2">
					否
				</item>
			</select>
		</say>
	</section>
	<section id="2" next-section="0">
		<gotoscene>scene3</gotoscene>
	</section>
	<section id="3" next-section="0">
		<say speaker="爱">真好</say>
	</section>
</scene>

=== weimingtom/galaxy_fork/galaxy/script/scene1.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="scene-def.xsd"
	id="0" bgimg="ff.jpg" bgm="03.wma">
   <!-- 贴张图 -->
   <section id="0">
       <img x="0" y="0" width="640" height="480">1/1.jpg</img>
       <say speaker="loli">
		姐，这把刀给你
	   </say>
       <sound>sakura.mp3</sound>
   </section>
	<section id="1">
		<img x="0" y="0" width="640" height="480">1/2.jpg</img>
		<say speaker="翠神">
		为啥？
		</say>
	</section>
	<section id="2">
		<img x="0" y="0" width="640" height="480">1/3.jpg</img>
		<say speaker="loli">
		没啥，天天看你用木头练刀觉得傻乎乎的
		</say>
		<sound>sakura.mp3</sound>
	</section>
	<section id="3">
		<img x="0" y="0" width="640" height="480">1/4.jpg</img>
		<say speaker="翠神">
		其实私有刀的，不过上次祭祀的时候掉湖里了
		</say>
	</section>
	<section id="4">
		<img x="0" y="0" width="640" height="480">1/4.jpg</img>
		<say speaker="翠神">
		要不你帮姐捞出来吧
		</say>
	</section>
	<section id="5">
		<img x="0" y="0" width="640" height="480">1/5.jpg</img>
		<say speaker="loli">
		私忽然想起私还没睡饱，老姐bye bye，私睡觉去了
		</say>
	</section>
	<section id="6">
       <gotoscene>scene3</gotoscene>
   </section>
</scene>
